export enum CurrencyE {
  BTC = 'BTC', // Bitcoin
  USDT = 'USDT', // Tether
  USDC = 'USDC', // USD Coin
  USD = 'USD', // US Dollar
  EUR = 'EUR', // Euro
  JPY = 'JPY', // Japanese Yen
  GBP = 'GBP', // British Pound Sterling
  AUD = 'AUD', // Australian Dollar
  CAD = 'CAD', // Canadian Dollar
  CHF = 'CHF', // Swiss Franc
  CNY = 'CNY', // Chinese Yuan Renminbi
  HKD = 'HKD', // Hong Kong Dollar
  NZD = 'NZD', // New Zealand Dollar
  SGD = 'SGD', // Singapore Dollar
  SEK = 'SEK', // Swedish Krona
  NOK = 'NOK', // Norwegian Krone
  KRW = 'KRW', // South Korean Won
  INR = 'INR', // Indian Rupee
  MXN = 'MXN', // Mexican Peso
  RUB = 'RUB', // Russian Ruble
  ZAR = 'ZAR', // South African Rand
  TRY = 'TRY', // Turkish Lira
  BRL = 'BRL', // Brazilian Real
  TWD = 'TWD', // New Taiwan Dollar
  PLN = 'PLN', // Polish Zloty
  THB = 'THB', // Thai Baht
  IDR = 'IDR', // Indonesian Rupiah
  DKK = 'DKK', // Danish Krone
  MYR = 'MYR', // Malaysian Ringgit
  PHP = 'PHP', // Philippine Peso
  AED = 'AED', // UAE Dirham
  SAR = 'SAR', // Saudi Riyal
  ILS = 'ILS', // Israeli New Shekel
  CZK = 'CZK', // Czech Koruna
  HUF = 'HUF', // Hungarian Forint
  CLP = 'CLP', // Chilean Peso
  PKR = 'PKR', // Pakistani Rupee
  NGN = 'NGN', // Nigerian Naira
  BDT = 'BDT', // Bangladeshi Taka
  EGP = 'EGP', // Egyptian Pound
  COP = 'COP', // Colombian Peso
  VND = 'VND', // Vietnamese Dong
  ARS = 'ARS', // Argentine Peso
  KWD = 'KWD', // Kuwaiti Dinar
  QAR = 'QAR', // Qatari Riyal
  OMR = 'OMR', // Omani Rial
  JOD = 'JOD', // Jordanian Dinar
  KES = 'KES', // Kenyan Shilling
  GHS = 'GHS', // Ghanaian Cedi
  TZS = 'TZS', // Tanzanian Shilling
  UGX = 'UGX', // Ugandan Shilling
  LKR = 'LKR', // Sri Lankan Rupee
  MAD = 'MAD', // Moroccan Dirham
  XAF = 'XAF', // Central African CFA Franc
  XOF = 'XOF', // West African CFA Franc
  BHD = 'BHD', // Bahraini Dinar
  UAH = 'UAH', // Ukrainian Hryvnia
}
